import type { Metadata } from "next";
import "./styles/globals.css";
import { monserrat } from "./styles/fonts";

export const metadata: Metadata = {
  title: "To Do App Next JS",
  description: "Generated by Luis Silva",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${monserrat.className} bg-slate-800`}>{children}</body>
    </html>
  );
}
